function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 27-May-2019 00:37:56

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fpass = 20;    % Passband Frequency
    % Fstop = 50;    % Stopband Frequency
    % Apass = 1;     % Passband Ripple (dB)
    % Astop = 80;    % Stopband Attenuation (dB)
    % Fs    = 2000;  % Sampling Frequency
    %
    % h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'MatchExactly', 'stopband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -1.97622204928019 0.98081472372878; 1 2 1 1 ...
        -1.94050103879754 0.945010698803406; 1 2 1 1 -1.91022784308708 ...
        0.914667149190922; 1 2 1 1 -1.88730812622473 0.891694167667335; 1 2 1 1 ...
        -1.8730518170043 0.877404727257461; 1 1 0 1 -0.934108613415219 0], ...
        'ScaleValues', [0.00114816861214679; 0.0011274150014656; ...
        0.00110982652596165; 0.00109651036065005; 0.00108822756329035; ...
        0.0329456932923905; 1]);
end

s = double(x);
y = step(Hd,s);

