function [dyaw,dpitch,droll] = dMatrix_to_dEuler(in1,in2)
%DMATRIX_TO_DEULER
%    [DYAW,DPITCH,DROLL] = DMATRIX_TO_DEULER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    12-Jul-2017 19:16:40

dr1_1 = in2(1);
dr2_1 = in2(2);
dr3_1 = in2(3);
dr3_2 = in2(6);
dr3_3 = in2(9);
r1_1 = in1(1);
r2_1 = in1(2);
r3_1 = in1(3);
r3_2 = in1(6);
r3_3 = in1(9);
t4 = imag(r1_1);
t5 = real(r2_1);
t2 = t4+t5;
t7 = imag(r2_1);
t8 = real(r1_1);
t3 = t7-t8;
t6 = t2.^2;
t9 = t3.^2;
t10 = t6+t9;
t11 = 1.0./t10;
dyaw = -dr1_1.*t2.*t11-dr2_1.*t3.*t11;
if nargout > 1
    dpitch = -dr3_1.*1.0./sqrt(-r3_1.^2+1.0);
end
if nargout > 2
    t14 = imag(r3_3);
    t15 = real(r3_2);
    t12 = t14+t15;
    t17 = imag(r3_2);
    t18 = real(r3_3);
    t13 = t17-t18;
    t16 = t12.^2;
    t19 = t13.^2;
    t20 = t16+t19;
    t21 = 1.0./t20;
    droll = -dr3_2.*t13.*t21-dr3_3.*t12.*t21;
end
