function [yaw,pitch,roll] = Matrix_to_Euler(in1)
%MATRIX_TO_EULER
%    [YAW,PITCH,ROLL] = MATRIX_TO_EULER(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    12-Jul-2017 19:16:39

r1_1 = in1(1);
r2_1 = in1(2);
r3_1 = in1(3);
r3_2 = in1(6);
r3_3 = in1(9);
yaw = angle(r1_1+r2_1.*1i);
if nargout > 1
    pitch = -asin(r3_1);
end
if nargout > 2
    roll = angle(r3_2.*1i+r3_3);
end
