function R = Quaternion_to_Matrix(in1)
%QUATERNION_TO_MATRIX
%    R = QUATERNION_TO_MATRIX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    12-Jul-2017 19:16:39

qw = in1(1,:);
qx = in1(2,:);
qy = in1(3,:);
qz = in1(4,:);
t2 = qx.*qy.*2.0;
t3 = qw.^2;
t4 = qx.^2;
t5 = qy.^2;
t6 = qz.^2;
t7 = qw.*qy.*2.0;
t8 = qx.*qz.*2.0;
t9 = qy.*qz.*2.0;
R = reshape([t3+t4-t5-t6,t2+qw.*qz.*2.0,-t7+t8,t2-qw.*qz.*2.0,t3-t4+t5-t6,t9+qw.*qx.*2.0,t7+t8,t9-qw.*qx.*2.0,t3-t4-t5+t6],[3,3]);
