function [dqFlexion,dqKnee] = Inverse_Kinematics_v(LA,LL,dLA,dLL)
%INVERSE_KINEMATICS_V
%    [DQFLEXION,DQKNEE] = INVERSE_KINEMATICS_V(LA,LL,DLA,DLL)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    25-Jul-2017 14:50:50

t2 = 1.0./LL.^2;
t3 = LL.^2;
t4 = t3+3.005264000000002e-2;
dqFlexion = dLA+dLL.*1.0./sqrt(t2.*t4.^2.*(-8.926893172654969e-1)+1.0).*(t2.*t4.*9.44822373393802e-1-1.889644746787604);
if nargout > 1
    t5 = t3.*1.889644746787604-1.001611186696901;
    dqKnee = LL.*dLL.*1.0./sqrt(-t5.^2+1.0).*3.779289493575208;
end
