function out1 = HeelSpringDeflectionEst(q4,q5,q6)
%HEELSPRINGDEFLECTIONEST
%    OUT1 = HEELSPRINGDEFLECTIONEST(Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    22-Aug-2019 16:26:24

t2 = cos(q6);
t3 = cos(q4);
t4 = cos(q5);
t5 = sin(q4);
t6 = sin(q5);
t7 = t3.*t6;
t8 = t4.*t5;
t9 = t7+t8;
t10 = sin(q6);
t11 = t3.*t4;
t13 = t5.*t6;
t12 = t11-t13;
t14 = t9.*t10.*3.059e1;
t15 = t2.*t9.*3.059e1;
t16 = t9.*t10.*1.269e1;
t17 = t10.*t12.*3.059e1;
t18 = t3.*4.741e1;
t19 = t5.*6.068e1;
t20 = t3.*t4.*2.0e1;
t21 = t3.*t6.*4.3476e2;
t22 = t4.*t5.*4.3476e2;
t23 = t2.*t9.*1.269e1;
t24 = t2.*t12.*3.059e1;
t25 = t10.*t12.*1.269e1;
t35 = t5.*t6.*2.0e1;
t36 = t14+t18+t19+t20+t21+t22-t23-t24-t25-t35;
t26 = abs(t36);
t27 = t3.*6.068e1;
t28 = t3.*t4.*4.3476e2;
t33 = t2.*t12.*1.269e1;
t38 = t5.*4.741e1;
t39 = t3.*t6.*2.0e1;
t40 = t4.*t5.*2.0e1;
t41 = t5.*t6.*4.3476e2;
t29 = t15+t16+t17+t27+t28-t33-t38-t39-t40-t41+1.2e2;
t30 = abs(t29);
t31 = -t14+t23+t24+t25;
t32 = abs(t31);
t34 = abs(t15+t16+t17-t33);
t37 = t26.^2;
t42 = t30.^2;
t43 = t37+t42;
t44 = 1.0./sqrt(t43);
t45 = 1.072595965035536e20;
out1 = -acos(7.071067811865475e1.*2.341777316484213e3.*t45.*6.265936630784442e-27)+asin(t44.*1.0./sqrt(t32.^2+t34.^2).*(t29.*t31+(t15+t16+t17-t2.*t12.*1.269e1).*(t14+t18+t19+t20+t21+t22-t2.*t9.*1.269e1-t5.*t6.*2.0e1-t2.*t12.*3.059e1-t10.*t12.*1.269e1)))+acos(t44.*t45.*(t37+t42-2.358194597351566e5).*3.914600586049742e-23);
