function [LA_new,dLA_new] = LegAngleForwardTransform(com_bp,LA,LL,dLA,dLL)
%LEGANGLEFORWARDTRANSFORM
%    [LA_NEW,DLA_NEW] = LEGANGLEFORWARDTRANSFORM(COM_BP,LA,LL,DLA,DLL)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    25-Jun-2019 13:04:56

t2 = sin(LA);
t3 = cos(LA);
t4 = LL.*t3;
LA_new = angle(com_bp+t4+LL.*t2.*1i);
if nargout > 1
    t5 = com_bp+t4;
    t6 = t5.^2;
    t7 = LL.^2;
    t8 = t2.^2;
    t9 = t7.*t8;
    t10 = t6+t9;
    t11 = 1.0./t10;
    t12 = 1.0./t5.^2;
    t13 = 1.0./t5;
    dLA_new = dLA.*t6.*t11.*(LL.*t3.*t13+t7.*t8.*t12)+dLL.*t6.*t11.*(t2.*t13-LL.*t2.*t3.*t12);
end
