function [LA,dLA] = LegAngleInverseTransform(com_bp,LA_new,LL,dLA_new,dLL)
%LEGANGLEINVERSETRANSFORM
%    [LA,DLA] = LEGANGLEINVERSETRANSFORM(COM_BP,LA_NEW,LL,DLA_NEW,DLL)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    25-Jun-2019 13:04:58

t2 = 1.0./LL;
t3 = sin(LA_new);
LA = LA_new+asin(com_bp.*t2.*t3);
if nargout > 1
    t4 = 1.0./LL.^2;
    t5 = com_bp.^2;
    t6 = t3.^2;
    t7 = -t4.*t5.*t6+1.0;
    t8 = 1.0./sqrt(t7);
    dLA = dLA_new.*(com_bp.*t2.*t8.*cos(LA_new)+1.0)-com_bp.*dLL.*t3.*t4.*t8;
end
