%BYTESTOCASSIESUMMARYBUS Convert a byte array to a CassieSummaryBus bus.

% Copyright 2018 Agility Robotics
% Generated automatically by BusModule.generateUnpackingSystem

classdef BytesToCassieSummaryBus < ...
    matlab.System & ...
    matlab.system.mixin.Propagates %#codegen

  % PROTECTED METHODS =====================================================
  methods (Access = protected)
    % SYSTEM CLASS METHODS ================================================
    function setupImpl(~)
      %SETUPIMPL Initialize System object.
    end % setupImpl

    function bus = stepImpl(~, bytes)
      %STEPIMPL System output and state update equations.

      bus = struct(...
        'version', reshape(char(bytes(1:8)), 1, 8), ...
        'totals', struct(...
          'onTime', double(typecast(bytes(9:12), 'single')), ...
          'activeTime', double(typecast(bytes(13:16), 'single')), ...
          'motorDistanceTraveled', double(typecast(bytes(17:56), 'single')), ...
          'jointDistanceTraveled', double(typecast(bytes(57:80), 'single')), ...
          'energyConsumed', double(typecast(bytes(81:84), 'single')), ...
          'overloads', typecast(bytes(85:88), 'uint32'), ...
          'fall', logical(bytes(89)), ...
          'etherCatErrors', double(typecast(bytes(90:93), 'single'))), ...
        'messages', bytes(94:221), ...
        'motor', struct(...
          'position', struct(...
            'min', double(typecast(bytes(222:261), 'single')), ...
            'max', double(typecast(bytes(262:301), 'single')), ...
            'mean', double(typecast(bytes(302:341), 'single')), ...
            'rms', double(typecast(bytes(342:381), 'single')), ...
            'var', double(typecast(bytes(382:421), 'single')), ...
            'std', double(typecast(bytes(422:461), 'single'))), ...
          'velocity', struct(...
            'min', double(typecast(bytes(462:501), 'single')), ...
            'max', double(typecast(bytes(502:541), 'single')), ...
            'mean', double(typecast(bytes(542:581), 'single')), ...
            'rms', double(typecast(bytes(582:621), 'single')), ...
            'var', double(typecast(bytes(622:661), 'single')), ...
            'std', double(typecast(bytes(662:701), 'single'))), ...
          'torqueActual', struct(...
            'min', double(typecast(bytes(702:741), 'single')), ...
            'max', double(typecast(bytes(742:781), 'single')), ...
            'mean', double(typecast(bytes(782:821), 'single')), ...
            'rms', double(typecast(bytes(822:861), 'single')), ...
            'var', double(typecast(bytes(862:901), 'single')), ...
            'std', double(typecast(bytes(902:941), 'single'))), ...
          'torqueCommanded', struct(...
            'min', double(typecast(bytes(942:981), 'single')), ...
            'max', double(typecast(bytes(982:1021), 'single')), ...
            'mean', double(typecast(bytes(1022:1061), 'single')), ...
            'rms', double(typecast(bytes(1062:1101), 'single')), ...
            'var', double(typecast(bytes(1102:1141), 'single')), ...
            'std', double(typecast(bytes(1142:1181), 'single'))), ...
          'temperature', struct(...
            'min', double(typecast(bytes(1182:1221), 'single')), ...
            'max', double(typecast(bytes(1222:1261), 'single')), ...
            'mean', double(typecast(bytes(1262:1301), 'single')), ...
            'rms', double(typecast(bytes(1302:1341), 'single')), ...
            'var', double(typecast(bytes(1342:1381), 'single')), ...
            'std', double(typecast(bytes(1382:1421), 'single')))), ...
        'joint', struct(...
          'position', struct(...
            'min', double(typecast(bytes(1422:1445), 'single')), ...
            'max', double(typecast(bytes(1446:1469), 'single')), ...
            'mean', double(typecast(bytes(1470:1493), 'single')), ...
            'rms', double(typecast(bytes(1494:1517), 'single')), ...
            'var', double(typecast(bytes(1518:1541), 'single')), ...
            'std', double(typecast(bytes(1542:1565), 'single'))), ...
          'velocity', struct(...
            'min', double(typecast(bytes(1566:1589), 'single')), ...
            'max', double(typecast(bytes(1590:1613), 'single')), ...
            'mean', double(typecast(bytes(1614:1637), 'single')), ...
            'rms', double(typecast(bytes(1638:1661), 'single')), ...
            'var', double(typecast(bytes(1662:1685), 'single')), ...
            'std', double(typecast(bytes(1686:1709), 'single')))), ...
        'battery', struct(...
          'voltage', struct(...
            'min', double(typecast(bytes(1710:1757), 'single')), ...
            'max', double(typecast(bytes(1758:1805), 'single')), ...
            'mean', double(typecast(bytes(1806:1853), 'single')), ...
            'rms', double(typecast(bytes(1854:1901), 'single')), ...
            'var', double(typecast(bytes(1902:1949), 'single')), ...
            'std', double(typecast(bytes(1950:1997), 'single'))), ...
          'current', struct(...
            'min', double(typecast(bytes(1998:2001), 'single')), ...
            'max', double(typecast(bytes(2002:2005), 'single')), ...
            'mean', double(typecast(bytes(2006:2009), 'single')), ...
            'rms', double(typecast(bytes(2010:2013), 'single')), ...
            'var', double(typecast(bytes(2014:2017), 'single')), ...
            'std', double(typecast(bytes(2018:2021), 'single'))), ...
          'power', struct(...
            'min', double(typecast(bytes(2022:2025), 'single')), ...
            'max', double(typecast(bytes(2026:2029), 'single')), ...
            'mean', double(typecast(bytes(2030:2033), 'single')), ...
            'rms', double(typecast(bytes(2034:2037), 'single')), ...
            'var', double(typecast(bytes(2038:2041), 'single')), ...
            'std', double(typecast(bytes(2042:2045), 'single'))), ...
          'stateOfCharge', struct(...
            'min', double(typecast(bytes(2046:2049), 'single')), ...
            'max', double(typecast(bytes(2050:2053), 'single')), ...
            'mean', double(typecast(bytes(2054:2057), 'single')), ...
            'rms', double(typecast(bytes(2058:2061), 'single')), ...
            'var', double(typecast(bytes(2062:2065), 'single')), ...
            'std', double(typecast(bytes(2066:2069), 'single'))), ...
          'temperature', struct(...
            'min', double(typecast(bytes(2070:2085), 'single')), ...
            'max', double(typecast(bytes(2086:2101), 'single')), ...
            'mean', double(typecast(bytes(2102:2117), 'single')), ...
            'rms', double(typecast(bytes(2118:2133), 'single')), ...
            'var', double(typecast(bytes(2134:2149), 'single')), ...
            'std', double(typecast(bytes(2150:2165), 'single')))), ...
        'targetPc', struct(...
          'taskExecutionTime', struct(...
            'min', double(typecast(bytes(2166:2169), 'single')), ...
            'max', double(typecast(bytes(2170:2173), 'single')), ...
            'mean', double(typecast(bytes(2174:2177), 'single')), ...
            'rms', double(typecast(bytes(2178:2181), 'single')), ...
            'var', double(typecast(bytes(2182:2185), 'single')), ...
            'std', double(typecast(bytes(2186:2189), 'single'))), ...
          'cpuTemperature', struct(...
            'min', double(typecast(bytes(2190:2193), 'single')), ...
            'max', double(typecast(bytes(2194:2197), 'single')), ...
            'mean', double(typecast(bytes(2198:2201), 'single')), ...
            'rms', double(typecast(bytes(2202:2205), 'single')), ...
            'var', double(typecast(bytes(2206:2209), 'single')), ...
            'std', double(typecast(bytes(2210:2213), 'single')))));
    end % stepImpl

    function resetImpl(~)
      %RESETIMPL Reset System object states.
    end % resetImpl

    function name_1 = getInputNamesImpl(~)
      %GETINPUTNAMESIMPL Return input port names for System block.
      name_1 = '';
    end % getInputNamesImpl

    function name_1 = getOutputNamesImpl(~)
      %GETOUTPUTNAMESIMPL Return output port names for System block.
      name_1 = '';
    end % getOutputNamesImpl

    % PROPAGATES CLASS METHODS ============================================
    function sz_1 = getOutputSizeImpl(~)
      %GETOUTPUTSIZEIMPL Get sizes of output ports.
      sz_1 = [1, 1];
    end % getOutputSizeImpl

    function dt_1 = getOutputDataTypeImpl(~)
      %GETOUTPUTDATATYPEIMPL Get data types of output ports.
      dt_1 = 'CassieSummaryBus';
    end % getOutputDataTypeImpl

    function cp_1 = isOutputComplexImpl(~)
      %ISOUTPUTCOMPLEXIMPL Complexity of output ports.
      cp_1 = false;
    end % isOutputComplexImpl

    function flag_1 = isOutputFixedSizeImpl(~)
      %ISOUTPUTFIXEDSIZEIMPL Fixed-size or variable-size output ports.
      flag_1 = true;
    end % isOutputFixedSizeImpl
  end % methods
end % classdef