%CASSIESUMMARYBUSTOBYTES Convert a CassieSummaryBus bus to a byte array.

% Copyright 2018 Agility Robotics
% Generated automatically by BusModule.generatePackingSystem

classdef CassieSummaryBusToBytes < ...
    matlab.System & ...
    matlab.system.mixin.Propagates %#codegen

  % PROTECTED METHODS =====================================================
  methods (Access = protected)
    % SYSTEM CLASS METHODS ================================================
    function setupImpl(~)
      %SETUPIMPL Initialize System object.
    end % setupImpl

    function bytes = stepImpl(~, bus)
      %STEPIMPL System output and state update equations.

      bytes = [...
        uint8(bus.version(:)); ...
        typecast(single(bus.totals.onTime)', 'uint8')'; ...
        typecast(single(bus.totals.activeTime)', 'uint8')'; ...
        typecast(single(bus.totals.motorDistanceTraveled)', 'uint8')'; ...
        typecast(single(bus.totals.jointDistanceTraveled)', 'uint8')'; ...
        typecast(single(bus.totals.energyConsumed)', 'uint8')'; ...
        typecast(bus.totals.overloads', 'uint8')'; ...
        uint8(bus.totals.fall); ...
        typecast(single(bus.totals.etherCatErrors)', 'uint8')'; ...
        bus.messages; ...
        typecast(single(bus.motor.position.min)', 'uint8')'; ...
        typecast(single(bus.motor.position.max)', 'uint8')'; ...
        typecast(single(bus.motor.position.mean)', 'uint8')'; ...
        typecast(single(bus.motor.position.rms)', 'uint8')'; ...
        typecast(single(bus.motor.position.var)', 'uint8')'; ...
        typecast(single(bus.motor.position.std)', 'uint8')'; ...
        typecast(single(bus.motor.velocity.min)', 'uint8')'; ...
        typecast(single(bus.motor.velocity.max)', 'uint8')'; ...
        typecast(single(bus.motor.velocity.mean)', 'uint8')'; ...
        typecast(single(bus.motor.velocity.rms)', 'uint8')'; ...
        typecast(single(bus.motor.velocity.var)', 'uint8')'; ...
        typecast(single(bus.motor.velocity.std)', 'uint8')'; ...
        typecast(single(bus.motor.torqueActual.min)', 'uint8')'; ...
        typecast(single(bus.motor.torqueActual.max)', 'uint8')'; ...
        typecast(single(bus.motor.torqueActual.mean)', 'uint8')'; ...
        typecast(single(bus.motor.torqueActual.rms)', 'uint8')'; ...
        typecast(single(bus.motor.torqueActual.var)', 'uint8')'; ...
        typecast(single(bus.motor.torqueActual.std)', 'uint8')'; ...
        typecast(single(bus.motor.torqueCommanded.min)', 'uint8')'; ...
        typecast(single(bus.motor.torqueCommanded.max)', 'uint8')'; ...
        typecast(single(bus.motor.torqueCommanded.mean)', 'uint8')'; ...
        typecast(single(bus.motor.torqueCommanded.rms)', 'uint8')'; ...
        typecast(single(bus.motor.torqueCommanded.var)', 'uint8')'; ...
        typecast(single(bus.motor.torqueCommanded.std)', 'uint8')'; ...
        typecast(single(bus.motor.temperature.min)', 'uint8')'; ...
        typecast(single(bus.motor.temperature.max)', 'uint8')'; ...
        typecast(single(bus.motor.temperature.mean)', 'uint8')'; ...
        typecast(single(bus.motor.temperature.rms)', 'uint8')'; ...
        typecast(single(bus.motor.temperature.var)', 'uint8')'; ...
        typecast(single(bus.motor.temperature.std)', 'uint8')'; ...
        typecast(single(bus.joint.position.min)', 'uint8')'; ...
        typecast(single(bus.joint.position.max)', 'uint8')'; ...
        typecast(single(bus.joint.position.mean)', 'uint8')'; ...
        typecast(single(bus.joint.position.rms)', 'uint8')'; ...
        typecast(single(bus.joint.position.var)', 'uint8')'; ...
        typecast(single(bus.joint.position.std)', 'uint8')'; ...
        typecast(single(bus.joint.velocity.min)', 'uint8')'; ...
        typecast(single(bus.joint.velocity.max)', 'uint8')'; ...
        typecast(single(bus.joint.velocity.mean)', 'uint8')'; ...
        typecast(single(bus.joint.velocity.rms)', 'uint8')'; ...
        typecast(single(bus.joint.velocity.var)', 'uint8')'; ...
        typecast(single(bus.joint.velocity.std)', 'uint8')'; ...
        typecast(single(bus.battery.voltage.min)', 'uint8')'; ...
        typecast(single(bus.battery.voltage.max)', 'uint8')'; ...
        typecast(single(bus.battery.voltage.mean)', 'uint8')'; ...
        typecast(single(bus.battery.voltage.rms)', 'uint8')'; ...
        typecast(single(bus.battery.voltage.var)', 'uint8')'; ...
        typecast(single(bus.battery.voltage.std)', 'uint8')'; ...
        typecast(single(bus.battery.current.min)', 'uint8')'; ...
        typecast(single(bus.battery.current.max)', 'uint8')'; ...
        typecast(single(bus.battery.current.mean)', 'uint8')'; ...
        typecast(single(bus.battery.current.rms)', 'uint8')'; ...
        typecast(single(bus.battery.current.var)', 'uint8')'; ...
        typecast(single(bus.battery.current.std)', 'uint8')'; ...
        typecast(single(bus.battery.power.min)', 'uint8')'; ...
        typecast(single(bus.battery.power.max)', 'uint8')'; ...
        typecast(single(bus.battery.power.mean)', 'uint8')'; ...
        typecast(single(bus.battery.power.rms)', 'uint8')'; ...
        typecast(single(bus.battery.power.var)', 'uint8')'; ...
        typecast(single(bus.battery.power.std)', 'uint8')'; ...
        typecast(single(bus.battery.stateOfCharge.min)', 'uint8')'; ...
        typecast(single(bus.battery.stateOfCharge.max)', 'uint8')'; ...
        typecast(single(bus.battery.stateOfCharge.mean)', 'uint8')'; ...
        typecast(single(bus.battery.stateOfCharge.rms)', 'uint8')'; ...
        typecast(single(bus.battery.stateOfCharge.var)', 'uint8')'; ...
        typecast(single(bus.battery.stateOfCharge.std)', 'uint8')'; ...
        typecast(single(bus.battery.temperature.min)', 'uint8')'; ...
        typecast(single(bus.battery.temperature.max)', 'uint8')'; ...
        typecast(single(bus.battery.temperature.mean)', 'uint8')'; ...
        typecast(single(bus.battery.temperature.rms)', 'uint8')'; ...
        typecast(single(bus.battery.temperature.var)', 'uint8')'; ...
        typecast(single(bus.battery.temperature.std)', 'uint8')'; ...
        typecast(single(bus.targetPc.taskExecutionTime.min)', 'uint8')'; ...
        typecast(single(bus.targetPc.taskExecutionTime.max)', 'uint8')'; ...
        typecast(single(bus.targetPc.taskExecutionTime.mean)', 'uint8')'; ...
        typecast(single(bus.targetPc.taskExecutionTime.rms)', 'uint8')'; ...
        typecast(single(bus.targetPc.taskExecutionTime.var)', 'uint8')'; ...
        typecast(single(bus.targetPc.taskExecutionTime.std)', 'uint8')'; ...
        typecast(single(bus.targetPc.cpuTemperature.min)', 'uint8')'; ...
        typecast(single(bus.targetPc.cpuTemperature.max)', 'uint8')'; ...
        typecast(single(bus.targetPc.cpuTemperature.mean)', 'uint8')'; ...
        typecast(single(bus.targetPc.cpuTemperature.rms)', 'uint8')'; ...
        typecast(single(bus.targetPc.cpuTemperature.var)', 'uint8')'; ...
        typecast(single(bus.targetPc.cpuTemperature.std)', 'uint8')'];
    end % stepImpl

    function resetImpl(~)
      %RESETIMPL Reset System object states.
    end % resetImpl

    function name_1 = getInputNamesImpl(~)
      %GETINPUTNAMESIMPL Return input port names for System block.
      name_1 = '';
    end % getInputNamesImpl

    function name_1 = getOutputNamesImpl(~)
      %GETOUTPUTNAMESIMPL Return output port names for System block.
      name_1 = '';
    end % getOutputNamesImpl

    % PROPAGATES CLASS METHODS ============================================
    function sz_1 = getOutputSizeImpl(~)
      %GETOUTPUTSIZEIMPL Get sizes of output ports.
      sz_1 = [2213, 1];
    end % getOutputSizeImpl

    function dt_1 = getOutputDataTypeImpl(~)
      %GETOUTPUTDATATYPEIMPL Get data types of output ports.
      dt_1 = 'uint8';
    end % getOutputDataTypeImpl

    function cp_1 = isOutputComplexImpl(~)
      %ISOUTPUTCOMPLEXIMPL Complexity of output ports.
      cp_1 = false;
    end % isOutputComplexImpl

    function flag_1 = isOutputFixedSizeImpl(~)
      %ISOUTPUTFIXEDSIZEIMPL Fixed-size or variable-size output ports.
      flag_1 = true;
    end % isOutputFixedSizeImpl
  end % methods
end % classdef